stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker build -t qiushaocloud/ub1604-nvm-node-base:latest
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker push qiushaocloud/ub1604-nvm-node-base:latest
  tags:
    - qiushaocloud-runner
