stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker build -t qiushaocloud/ub1604-nvm-node-base:latest .
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username qiushaocloud --password LsVQg6J3iEX9GxDLo4W8
    - docker push qiushaocloud/ub1604-nvm-node-base:latest
  tags:
    - qiushaocloud-runner
